#!/usr/bin/perl -l

#use warnings;
use strict;
use Data::Dumper;

my @lines = <>;
chomp @lines;

my $d = [];
for my $line (@lines) {
  my $h = {};
  #my ($year, $month, $day, $hour, $minute, $action, $id) = $line =~ m/\[(\d+)-(\d+)-(\d+) (\d+):(\d+)\] (wakes up|falls asleep|Guard #(\d+) begins shift)/;
  @{$h}{qw/year month day hour minute action id/} = $line =~ m/\[(\d+)-(\d+)-(\d+) (\d+):(\d+)\] (wakes up|falls asleep|Guard #(\d+) begins shift)/;
  $h->{line} = $line;
  push @$d, $h;
}

@$d = sort {
        $a->{year} <=> $b->{year} or
        $a->{month} <=> $b->{month} or
        $a->{day} <=> $b->{day} or
        $a->{hour} <=> $b->{hour} or
        $a->{minute} <=> $b->{minute}
      } @$d;

print Dumper $d;

my $guard_score = {};
my $sleep_minutes = {};
my $current_guard;
my $sleep_start;
for my $event (@$d) {
  if ($event->{action} =~ /^Guard/) {
    $current_guard = $event->{id};
  } elsif ($event->{action} eq "falls asleep") {
    $sleep_start = $event->{minute};
  } elsif ($event->{action} eq "wakes up") {
    $guard_score->{$current_guard} += $event->{minute} - $sleep_start;
    for my $minute ($sleep_start..($event->{minute}-1)) {
      $sleep_minutes->{$current_guard}[$minute]++;
    }
  }
}

print Dumper $guard_score;
my ($sleepy_guard) = reverse sort { $guard_score->{$a} <=> $guard_score->{$b} } keys %$guard_score;
print $sleepy_guard;
my $i = 0;
my $most_sleepy_minute;
for my $sleep_count (@{$sleep_minutes->{$sleepy_guard}}) {
  $most_sleepy_minute = $i if $sleep_minutes->{$sleepy_guard}[$most_sleepy_minute] < $sleep_count;
  $i++;
}
print "guard: $sleepy_guard minute: $most_sleepy_minute, ans: ". ($sleepy_guard*$most_sleepy_minute);
