#!/usr/bin/perl

use warnings;
use strict;
use feature 'say';
use Data::Dumper;

my $serial = 7803;

my $grid = [];

sub rack_id {
  my ($x) = @_;
  return $x + 10
}

sub hundreds_digit {
  int($_[0] % 1000 / 100)
}

sub grid_val {
  my ($x, $y, $serial) = @_;
  my $result = rack_id($x); # rack id
  $result *= $y;
  $result += $serial;
  $result *= rack_id($x);
  $result = hundreds_digit $result;
  $result -= 5;
}

sub sum_three {
  my ($x, $y) = @_;
  die "oob ($x, $y)" if $x > 298 or $y > 298;
  die "oob ($x, $y)" if $x < 1 or $y < 1;
  my $sum = 0;
  for my $i ($x..($x + 2)) {
    for my $j ($y..($y + 2)) {
      $sum += $grid->[$i][$j];
    }
  }
  return $sum;
}

sub no_cache_sum_n {
  my ($x, $y, $n) = @_;
  die "oob ($x, $y)" if $x + $n > 300 or $y + $n > 300;
  die "oob ($x, $y)" if $x < 1 or $y < 1;
  my $sum = 0;

  for my $i ($x..($x + $n - 1)) {
    for my $j ($y..($y + $n - 1)) {
      $sum += $grid->[$i][$j];
    }
  }
  return $sum;
}

our $sum_cache =[];
sub sum_n {
  my ($x, $y, $n) = @_;
  die "oob ($x, $y)" if $x + $n > 300 or $y + $n > 300;
  die "oob ($x, $y)" if $x < 1 or $y < 1;
  my $sum = 0;

  if ($n == 1) {
    for my $i ($x..($x + $n - 1)) {
      for my $j ($y..($y + $n - 1)) {
        $sum += $grid->[$i][$j];
        $sum_cache->[$i][$j] = $sum;
      }
    }
  } else {
    # n > 1, we have a cache of the previous square
    my $edge_sum = 0;
    for my $i ($x..($x + $n - 1)) { $edge_sum += $grid->[$i][$y + $n - 1] }
    for my $j ($y..($y + $n - 2)) { $edge_sum += $grid->[$x + $n - 1][$j] }
    $sum = $sum_cache->[$x][$y] + $edge_sum;
    $sum_cache->[$x][$y] = $sum;
  }
  return $sum;
}

sub print_three {
  my ($x, $y) = @_;
  for my $j ($y..($y + 2)) {
    for my $i ($x..($x + 2)) {
      #print $grid->[$i][$j];
      print sprintf " %+ d", $grid->[$i][$j];
    }
    print "\n";
  }
}

sub print_n {
  my ($x, $y, $n) = @_;
  for my $j ($y..($y + $n - 1)) {
    for my $i ($x..($x + $n - 1)) {
      #print $grid->[$i][$j];
      print sprintf " %+ d", $grid->[$i][$j];
    }
    print "\n";
  }
}

say grid_val(122,79, 57);
say grid_val 217,196, 39;
say grid_val 101,153, 71;

for my $i (1..300) {
  for my $j (1..300) {
    $grid->[$i][$j] = grid_val($i, $j, $serial)
  }
}

print_n(1, 1, 4);

my $biggest = [0,0,0, 0];
for my $n (1..300) {
  say "doing n $n";
  for my $i (1..(300 - $n)) {
    for my $j (1..(300 - $n)) {
      # print sprintf " %+ d", $grid->[$i][$j];
      my $sum = sum_n $i, $j, $n;
#      my $no_cache_sum_n = no_cache_sum_n $i, $j, $n;
#      say "($i, $j): $sum, $no_cache_sum_n";
      $biggest = [$i, $j, $n, $sum] if $biggest->[3] < $sum;
    }
  }
}

print Dumper $biggest;
print_n($biggest->[0], $biggest->[1], $biggest->[2])
